import type { Receit } from './types';

export const sampleReceits: Receit[] = [
  {
    id: '1',
    title: 'Develop User Authentication',
    description: 'Implement JWT-based authentication for the main application.',
    priority: 'High',
    category: 'Development',
    effort: 8,
    startDate: new Date('2024-08-01'),
    dueDate: new Date('2024-08-15'),
    status: 'Done',
    linkedReceits: [],
  },
  {
    id: '2',
    title: 'Design Marketing Landing Page',
    description: 'Create mockups and wireframes for the new landing page.',
    priority: 'Medium',
    category: 'Marketing',
    effort: 5,
    startDate: new Date('2024-08-05'),
    dueDate: new Date('2024-08-12'),
    status: 'Done',
    linkedReceits: [],
  },
  {
    id: '3',
    title: 'Setup CI/CD Pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment.',
    priority: 'High',
    category: 'Development',
    effort: 5,
    startDate: new Date('2024-08-16'),
    dueDate: new Date('2024-08-22'),
    status: 'To-Do',
    linkedReceits: ['1'],
  },
  {
    id: '4',
    title: 'Write Q3 Blog Post',
    description: 'Draft a blog post about our new features.',
    priority: 'Low',
    category: 'Marketing',
    effort: 3,
    startDate: new Date('2024-08-20'),
    dueDate: new Date('2024-09-01'),
    status: 'To-Do',
    linkedReceits: [],
  },
  {
    id: '5',
    title: 'Plan Annual Company Retreat',
    description: 'Organize logistics, budget, and activities for the retreat.',
    priority: 'Medium',
    category: 'Personal',
    effort: 10,
    startDate: new Date('2024-08-10'),
    dueDate: new Date('2024-09-15'),
    status: 'To-Do',
    linkedReceits: [],
  },
  {
    id: '6',
    title: 'Refactor Database Schema',
    description: 'Optimize the database schema for better performance.',
    priority: 'Medium',
    category: 'Development',
    effort: 8,
    startDate: new Date('2024-09-01'),
    dueDate: new Date('2024-09-10'),
    status: 'To-Do',
    linkedReceits: ['3'],
  },
];
